---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: staging-issuer
  namespace: amber
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: traefik