---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress3-ingress
  namespace: amber
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: "staging-issuer"
spec:
  tls:
   - hosts:
       - wordpress3.eks.zacharyironside.com
     secretName: wordpress3-ingress-cert
  rules:
    - host: wordpress3.eks.zacharyironside.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  wordpress3
                port:
                  number: 80
--- 
apiVersion: v1
kind: Service
metadata:
  name: wordpress3
  namespace: amber
spec:
  selector:
    app: wordpress3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress3
  namespace: amber
  labels:
    app: wordpress3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress3
  template:
    metadata:
      labels:
        app: wordpress3
    spec:
      containers:
      - name: wordpress3
        image: wordpress
        ports:
        - containerPort: 80
        env:
            - name: DB_HOST
              value: mysql.default
            - name: DB_USER
              value: wordpress3
            - name: DB_PASS
              value: secretword